// Football-data.org returns national team names in English ("Spain", "England"). This
// translates the common ones (World Cup / Euro / Copa América participants) to Portuguese.
export const COUNTRY_NAME_PT: Record<string, string> = {
  Albania: "Albânia",
  Algeria: "Argélia",
  Argentina: "Argentina",
  Armenia: "Armênia",
  Australia: "Austrália",
  Austria: "Áustria",
  Belgium: "Bélgica",
  Bolivia: "Bolívia",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  Brazil: "Brasil",
  Bulgaria: "Bulgária",
  Cameroon: "Camarões",
  Canada: "Canadá",
  Chile: "Chile",
  China: "China",
  Colombia: "Colômbia",
  "Costa Rica": "Costa Rica",
  Croatia: "Croácia",
  Cyprus: "Chipre",
  Czechia: "Tchéquia",
  "Czech Republic": "República Tcheca",
  Denmark: "Dinamarca",
  Ecuador: "Equador",
  Egypt: "Egito",
  England: "Inglaterra",
  Estonia: "Estônia",
  Finland: "Finlândia",
  France: "França",
  Georgia: "Geórgia",
  Germany: "Alemanha",
  Ghana: "Gana",
  Greece: "Grécia",
  Hungary: "Hungria",
  Iceland: "Islândia",
  Iran: "Irã",
  Iraq: "Iraque",
  Ireland: "Irlanda",
  "Republic of Ireland": "Irlanda",
  Israel: "Israel",
  Italy: "Itália",
  Ivory_Coast: "Costa do Marfim",
  "Ivory Coast": "Costa do Marfim",
  Jamaica: "Jamaica",
  Japan: "Japão",
  Kazakhstan: "Cazaquistão",
  Kosovo: "Kosovo",
  Latvia: "Letônia",
  Lithuania: "Lituânia",
  Luxembourg: "Luxemburgo",
  Malta: "Malta",
  Mexico: "México",
  Moldova: "Moldávia",
  Montenegro: "Montenegro",
  Morocco: "Marrocos",
  Netherlands: "Holanda",
  "New Zealand": "Nova Zelândia",
  "North Macedonia": "Macedônia do Norte",
  "Northern Ireland": "Irlanda do Norte",
  Norway: "Noruega",
  Nigeria: "Nigéria",
  Panama: "Panamá",
  Paraguay: "Paraguai",
  Peru: "Peru",
  Poland: "Polônia",
  Portugal: "Portugal",
  Qatar: "Catar",
  Romania: "Romênia",
  Russia: "Rússia",
  "San Marino": "San Marino",
  "Saudi Arabia": "Arábia Saudita",
  Scotland: "Escócia",
  Senegal: "Senegal",
  Serbia: "Sérvia",
  Slovakia: "Eslováquia",
  Slovenia: "Eslovênia",
  "South Korea": "Coreia do Sul",
  "Korea Republic": "Coreia do Sul",
  Spain: "Espanha",
  Sweden: "Suécia",
  Switzerland: "Suíça",
  Tunisia: "Tunísia",
  Turkey: "Turquia",
  Türkiye: "Turquia",
  Ukraine: "Ucrânia",
  "United States": "Estados Unidos",
  USA: "Estados Unidos",
  Uruguay: "Uruguai",
  Venezuela: "Venezuela",
  Wales: "País de Gales",
};
